SRC_URI += " git://github.com/heroku/abnfc.git;branch=master;destsuffix=git-deps/abnfc;name=abnfc"
SRCREV_abnfc = "856c77cce8f0dd66bfe95f3ec4041f9f59b742bb"

SRC_URI += " git://github.com/boundary/bear.git;branch=master;destsuffix=git-deps/bear;name=bear"
SRCREV_bear = "119234548783af19b8ec75c879c5062676b92571"

SRC_URI += " git://github.com/bitwalker/conform.git;protocol=https;branch=master;destsuffix=git-deps/conform;name=conform"
SRCREV_conform = "678dbfca6e7a94dd9d9214e6dbddf8b3ddb35dbf"

SRC_URI += " git://github.com/bitwalker/conform_exrm.git;protocol=https;branch=master;destsuffix=git-deps/conform_exrm;name=conform_exrm"
SRCREV_conform_exrm = "0f7fdef4cc31ff7e127917a6601fb5f4762d44ad"

SRC_URI += " git://github.com/alfert/coverex.git;protocol=https;branch=master;destsuffix=git-deps/coverex;name=coverex"
SRCREV_coverex = "38c21c9cfac5e5df27cad0f4d8467fd94e824434"

SRC_URI += " git://github.com/uwiger/edown.git;protocol=https;branch=master;destsuffix=git-deps/edown;name=edown"
SRCREV_edown = "754be25f71a04099c83f3ffdff268e70beeb0021"

SRC_URI += " git://github.com/heroku/ex_uri.git;protocol=https;branch=master;destsuffix=git-deps/ex_uri;name=ex_uri"
SRCREV_ex_uri = "16f26db7026493d2934f615f8884fad42675f00e"

SRC_URI += " git://github.com/xerions/exlager.git;protocol=https;branch=master;destsuffix=git-deps/exlager;name=exlager"
SRCREV_exlager = "f43abf432da30ca3934b6a4d66a44c74d3f27f1b"

SRC_URI += " git://github.com/Feuerlabs/exometer_core.git;protocol=https;branch=master;destsuffix=git-deps/exometer_core;name=exometer_core"
SRCREV_exometer_core = "9206b28d045b395abd1b86cc794223ec9aeeb0ea"

SRC_URI += " git://github.com/travelping/exometer_fetch.git;protocol=https;branch=master;destsuffix=git-deps/exometer_fetch;name=exometer_fetch"
SRCREV_exometer_fetch = "1a0d4f033ce0e8e6bad8c40b739d4c76b0dc546b"

SRC_URI += " git://github.com/travelping/exometer_influxdb.git;protocol=https;branch=master;destsuffix=git-deps/exometer_influxdb;name=exometer_influxdb"
SRCREV_exometer_influxdb = "e5c88f73a9dec5cf479e80f867ce3ac3d651c802"

SRC_URI += " git://github.com/bitwalker/exrm.git;protocol=https;branch=master;destsuffix=git-deps/exrm;name=exrm"
SRCREV_exrm = "915370fb4baeb7a04ab02ee52b5e7322db7fbabe"

SRC_URI += " git://github.com/liveforeverx/exrun.git;protocol=https;branch=master;destsuffix=git-deps/exrun;name=exrun"
SRCREV_exrun = "fc516628906cb571f832ade2b484e2ed5df40cc6"

SRC_URI += " git://github.com/RoadRunnr/ezmq.git;protocol=https;branch=fix-socket-crash;destsuffix=git-deps/ezmq;name=ezmq"
SRCREV_ezmq = "a77378f0cb716b5293be6f69bdc99ed137a509c4"

SRC_URI += " git://github.com/folsom-project/folsom;branch=master;destsuffix=git-deps/folsom;name=folsom"
SRCREV_folsom = "38e2cce7c64ce1f0a3a918d90394cfc0a940b1ba"

SRC_URI += " git://github.com/travelping/gen_listener_tcp.git;protocol=https;branch=master;destsuffix=git-deps/gen_listener_tcp;name=gen_listener_tcp"
SRCREV_gen_listener_tcp = "fb9626d172b09e6448d36f23e6055adf75189bfe"

SRC_URI += " git://github.com/DeadZen/goldrush.git;protocol=https;branch=master;destsuffix=git-deps/goldrush;name=goldrush"
SRCREV_goldrush = "212299233c7e7eb63a97be2777e1c05ebaa58dbe"

SRC_URI += " git://github.com/travelping/hello.git;protocol=https;branch=master;destsuffix=git-deps/hello;name=hello"
SRCREV_hello = "1205823fc2e7b617e16998919f152d509f54a9e7"

SRC_URI += " git://github.com/tolbrino/hut.git;branch=master;destsuffix=git-deps/hut;name=hut"
SRCREV_hut = "025540398478ab6f95932c3234382ac5bb21ad3e"

SRC_URI += " git://github.com/basho/lager.git;protocol=https;branch=master;destsuffix=git-deps/lager;name=lager"
SRCREV_lager = "bce5504a955e52be8d5cf4b3c6b1fcd898ab5756"

SRC_URI += " git://github.com/eproxus/meck.git;protocol=https;branch=master;destsuffix=git-deps/meck;name=meck"
SRCREV_meck = "17b0ea5b7d9c93af3a52b5152c6bee14302b3885"

SRC_URI += " git://github.com/xerions/metricman.git;protocol=https;branch=master;destsuffix=git-deps/metricman;name=metricman"
SRCREV_metricman = "8382b2650c09975f8df9ac154b776bdfb512f1de"

SRC_URI += " git://github.com/jjh42/mock.git;protocol=https;branch=master;destsuffix=git-deps/mock;name=mock"
SRCREV_mock = "70ba88fe210cca3466696dc81834f3dbcd63f209"

SRC_URI += " git://github.com/uwiger/parse_trans.git;branch=master;destsuffix=git-deps/parse_trans;name=parse_trans"
SRCREV_parse_trans = "a210adafdfbb904d156d8f22abd5fb58fc17de1e"

SRC_URI += " git://github.com/erlware/relx.git;protocol=https;branch=master;destsuffix=git-deps/relx;name=relx"
SRCREV_relx = "53a87edc5285042355b545075440985dd3037bc6"

SRC_URI += " git://github.com/uwiger/setup.git;protocol=https;branch=master;destsuffix=git-deps/setup;name=setup"
SRCREV_setup = "4de9ad24f6f89a3f9996f8f02329bc20d67f2d9e"

SRC_URI += " git://github.com/travelping/yang.git;protocol=https;branch=master;destsuffix=git-deps/yang;name=yang"
SRCREV_yang = "922128924e7e62115ea7b36d8064b524e27e6615"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/bbmustache-1.0.4.tar;subdir=hex-deps/bbmustache;name=bbmustache"
SRC_URI[bbmustache.md5sum] = "8c9ae09dd8e2c3eef4c71199e87373ce"
SRC_URI[bbmustache.sha256sum] = "03b0d47db66e86df993896dce7578d7e4aae5f84636809b45fa8a3e34ee59b12"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/certifi-0.3.0.tar;subdir=hex-deps/certifi;name=certifi"
SRC_URI[certifi.md5sum] = "09970b56a4d27eb21f17ca94971207a2"
SRC_URI[certifi.sha256sum] = "42ae85fe91c038a634a5fb8d0c77f4fc581914c508f087c7138e9366a1517f6a"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/cf-0.2.1.tar;subdir=hex-deps/cf;name=cf"
SRC_URI[cf.md5sum] = "0b40f26fa0cd27f89b9e3cce3f9a2dd5"
SRC_URI[cf.sha256sum] = "baee9aa7ec2dfa3cb4486b67211177caa293f876780f0b313b45718edef6a0a5"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/cowboy-1.0.2.tar;subdir=hex-deps/cowboy;name=cowboy"
SRC_URI[cowboy.md5sum] = "4a50d676d3b75803d5ba1070c712653b"
SRC_URI[cowboy.sha256sum] = "aeba3815a73985ce872cb480814771c15b8dac15894fb9ee4c135800ae883fd3"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/cowlib-1.0.1.tar;subdir=hex-deps/cowlib;name=cowlib"
SRC_URI[cowlib.md5sum] = "fe7fb4c91234ee38fede7a3ad12fdb81"
SRC_URI[cowlib.sha256sum] = "4f6b470c0c4cfc261eeff798b20d8e23a9d88ff595b2b19f4173fb125c23bd53"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/erlware_commons-0.21.0.tar;subdir=hex-deps/erlware_commons;name=erlware_commons"
SRC_URI[erlware_commons.md5sum] = "8427291572cd6486ed9df7fcdf413d2d"
SRC_URI[erlware_commons.sha256sum] = "e70a95762458a489dc37fe869f41517bd43c130e156ef08462f90c534300ab3f"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/getopt-0.8.2.tar;subdir=hex-deps/getopt;name=getopt"
SRC_URI[getopt.md5sum] = "7bec0d9e2fae129b0c8861c018a855cc"
SRC_URI[getopt.sha256sum] = "736e6db3679fbbad46373efb96b69509f8e420281635e9d92989af9f0a0483f7"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/hackney-1.4.6.tar;subdir=hex-deps/hackney;name=hackney"
SRC_URI[hackney.md5sum] = "eb4f116c5b18c2659bd152b699903f62"
SRC_URI[hackney.sha256sum] = "5b8f9ca492eb42c78815480d03358a3a1b8ba5c1bb5d63f1ebfb71eb746df3bb"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/httpoison-0.7.2.tar;subdir=hex-deps/httpoison;name=httpoison"
SRC_URI[httpoison.md5sum] = "ce49ae44ad73650b208b4884ada2cdb4"
SRC_URI[httpoison.sha256sum] = "afb76dd9c001771b3b50ebe4f06e484db85e057e5cd3541e18fed8b652c1089e"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/idna-1.0.2.tar;subdir=hex-deps/idna;name=idna"
SRC_URI[idna.md5sum] = "c1c9622a358eded9e08b5ab523165af7"
SRC_URI[idna.sha256sum] = "a5d645e307aa4f67efe31682f720b7eaf431ab148b3d6fb66cbaf6314499610f"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/jsx-2.6.2.tar;subdir=hex-deps/jsx;name=jsx"
SRC_URI[jsx.md5sum] = "1b906e79ac6bde7eba22d4684825a3a6"
SRC_URI[jsx.sha256sum] = "6bfccb6461cc3c7d5cc63f3e69ffeb2f1f8de50eca5980065311c056a69a907f"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/mimerl-1.0.0.tar;subdir=hex-deps/mimerl;name=mimerl"
SRC_URI[mimerl.md5sum] = "2462daa0a2eae770a2b48eb6f6142a80"
SRC_URI[mimerl.sha256sum] = "a30b01104a29bd3a363db8646e4ce0f7980f9ecd23a98707c46c3ced918c41b4"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/msgpack-0.6.0.tar;subdir=hex-deps/msgpack;name=msgpack"
SRC_URI[msgpack.md5sum] = "7fb135bf5189e80d8ae66a2a08c10ca3"
SRC_URI[msgpack.sha256sum] = "07d0fdab2f3874fc1a4e41259aff98cc52dac6011e327cf181a07a584f2e4084"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/neotoma-1.7.3.tar;subdir=hex-deps/neotoma;name=neotoma"
SRC_URI[neotoma.md5sum] = "94ac8ec1416f4801cd2af1ca930c3d01"
SRC_URI[neotoma.sha256sum] = "2da322b9b1567ffa0706a7f30f6bbbde70835ae44a1050615f4b4a3d436e0f28"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/poison-1.4.0.tar;subdir=hex-deps/poison;name=poison"
SRC_URI[poison.md5sum] = "7cc89c467c87d1e98076d95819153c04"
SRC_URI[poison.sha256sum] = "b2715aaeb9f549f4e30739d43993e3c1b1053a4ed69d50c660621bdd1eb96606"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/providers-1.6.0.tar;subdir=hex-deps/providers;name=providers"
SRC_URI[providers.md5sum] = "ac0502840b173d974df65e61024a40ff"
SRC_URI[providers.sha256sum] = "0f6876529a613d34224de8c61d3660388eb981142360f2699486d8536050ce2f"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/ranch-1.1.0.tar;subdir=hex-deps/ranch;name=ranch"
SRC_URI[ranch.md5sum] = "79e3789dacb1d50a85c6dce87d1ae3d3"
SRC_URI[ranch.sha256sum] = "98ade939e63e6567da5dec5bc5bd93cbdc53d53f8b1aa998adec60dc4057f048"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/recon-2.2.1.tar;subdir=hex-deps/recon;name=recon"
SRC_URI[recon.md5sum] = "c4f75d12412a6a0208f41043195f50b5"
SRC_URI[recon.sha256sum] = "6c548ad0f4916495a78977674a251847869f85b5125b7c2a44da3178955adfd1"

SRC_URI += " https://s3.amazonaws.com/s3.hex.pm/tarballs/ssl_verify_hostname-1.0.5.tar;subdir=hex-deps/ssl_verify_hostname;name=ssl_verify_hostname"
SRC_URI[ssl_verify_hostname.md5sum] = "ba549a23145c6bdb15ba2f84b6187ad8"
SRC_URI[ssl_verify_hostname.sha256sum] = "f2cb11e6144e10ab39d1e14bf9fb2437b690979c70bf5428e9dc4bfaf1dfeabf"

