#!/bin/sh
### BEGIN INIT INFO
# Provides:		ipctld
# Required-Start:	$remote_fs $syslog $networking $ethctld
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	ROFL Ethernet Control Deamon
### END INIT INFO
#
# Do not configure this file.
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=ipctld
DAEMON=/usr/sbin/$NAME
DESC="ROFL IPCTLD"
CONF="/etc/rofl/$NAME.conf"
ARGS="-D -c $CONF"

test -r $CONF || exit 0

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S -x "$DAEMON" -- $ARGS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON"
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon -K -x "$DAEMON"
	sleep 1
	start-stop-daemon -S -x "$DAEMON" -- $ARGS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
