#!/bin/sh
echo
echo "Creating hashed links..."
rm -f $SYSROOT/etc/ssl/certs/*.0
for f in $SYSROOT/etc/ssl/certs/*.pem; do
    n=$(openssl x509 -hash -in $f -noout) > /dev/null 2>&1
    if [ ! -e "$SYSROOT/etc/ssl/certs/$n.0" ]
    then
        f_image="/etc/ssl/certs/$(basename $f)"
        ln -s $f_image $SYSROOT/etc/ssl/certs/$n.0
    fi
done
return 0
