#!/bin/sh

set -e
table_families="iptables ip6tables ebtables"

case "$1" in
	"restore")
		for iptaf in $table_families; do
			if [ "$(which ${iptaf}-restore )" ]; then
				if [ -e /etc/${iptaf}-state ]; then
					${iptaf}-restore < /etc/${iptaf}-state
				else
					echo "no saved ${iptaf} state found. please run $0 save."
				fi
			fi
		done
	;;
	"save")
		for iptaf in $table_families; do
			if [ "$(which ${iptaf}-save )" ]; then
				${iptaf}-save > /etc/${iptaf}-state
				echo "saved ${iptaf} state"
			fi
		done
	;;
	*)
		echo "syntax: $0 {save,restore}"
	;;
esac
exit 0
