#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
set timeout=10
menuentry "__DISTRO_NAME__" {
    set root=(hd0,3)
    linux /@/boot/bzImage root=__ROOTFS__ rw rootflags=subvol=@ __CONSOLE__ __VIDEO_MODE__ __VGA_MODE__ panic=30
}

